# Generated by Django 4.2.5 on 2023-10-13 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='fk_syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.syllabus', verbose_name='Syllabus'),
        ),
    ]
