# Generated by Django 4.2.5 on 2023-10-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_content_content_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classschedule',
            old_name='fk_nstructor',
            new_name='fk_instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='fk_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='quizes',
            name='fk_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='quizqanda',
            name='quizAnswer',
            field=models.CharField(max_length=20),
        ),
    ]
