# Generated by Django 4.2.5 on 2023-10-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_fk_nstructor_classschedule_fk_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizes',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='fk_quizQAndAID',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='maxScore',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='userScore',
        ),
        migrations.AddField(
            model_name='quizes',
            name='quiz_url',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='QuizQAndA',
        ),
    ]
