# Generated by Django 4.2.5 on 2023-10-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_quizes_enddate_remove_quizes_fk_quizqandaid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_file',
        ),
        migrations.AddField(
            model_name='content',
            name='content_url',
            field=models.URLField(null=True),
        ),
    ]
