# Generated by Django 4.2.5 on 2023-10-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_content_content_file_content_content_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content_url',
            new_name='contents_url',
        ),
    ]
