# Generated by Django 4.2.5 on 2023-10-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_content_url_content_contents_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='contents_url',
            new_name='content_url',
        ),
    ]
