# Generated by Django 4.2.5 on 2023-10-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_contents_url_content_content_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contentTitle',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
