# Generated by Django 4.2.5 on 2023-10-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_content_contenttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profilePicture',
            field=models.ImageField(blank=True, default=1, null=True, upload_to=''),
        ),
    ]
